//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerieFlixProyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Series
    {
        public int ID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar un Titulo.")]
        [DisplayName("Titulo")]
        public string Titulo { get; set; }
        public int Genero { get; set; }
        public int Idioma { get; set; }
    
        public virtual Generos Generos { get; set; }
        public virtual Idiomas Idiomas { get; set; }
    }
}
